---
- hosts: webserver
  remote_user: remote_username
  become: yes
  become_method: sudo
  tasks:
    - name: Build Docker image from Dockerfile
      docker_image:
        name: web
        state: build
        
    - name: Running the container
      docker_container:
        image: web:latest
        state: running
