---
- hosts: web
  vars: 
    http_port: 80
    doc_root: /var/www/html/ansible 

  tasks: 
  - name: install Apache service on Ubuntu
    yum: name=apache2 state=present
    when: ansible_os_family == "Ubuntu"

  - name: start Apache service on RedHat
    yum: name=httpd state=present
    when: ansible_os_family == "RedHat"

  - name: start Apache service on RedHat
    service: name=httpd state=started
    when: ansible_os_family == "RedHat"

  - name: install Apache service on Ubuntu
    service: name=apache2 state=started
    when: ansible_os_family == "Ubuntu"

  - name: install Apache service on CentOS
    yum: name=apache2 state=present
    when: ansible_os_family == "CentOS"

  - name: start Apache service on CentOS
    service: name=apache2 state=started
    when: ansible_os_family == "CentOS"

  - name: Deploy static site file
    copy: src=templates/index.html dest=/var/www/html/index.html
    notify: 
      - Restart Apache

  - name: Create a new site location
    file: path={{doc_root}} state=directory

  - name: download mario
    get_url: url="http://clipart-library.com/images/ziX48a4kT.jpg" dest={{doc_root}}/mario.jpg

  - name: Copy the template
    template: src=templates/info.j2 dest={{doc_root}}/info.html

  - name: Copy jar
    copy: src=templates/atmosphere.jar dest={{doc_root}}/atmosphere.jar

  - name: Install jar
    shell: nohup /bin/java -jar {{doc_root}}/atmosphere.jar &

  - name: Install java
    yum: name=java state=present

  handlers: 
  - name: Restart Apache
    service: name=httpd state=restarted
